import { init } from "./sdk-base";

const script = document.currentScript!;

init({
	getDefault: () => script.dataset,
	getTitle: fen => fen + "\n\nGenerated by https://mutsuntsai.github.io/fen-tool",
});
