import { makeOption } from "../option";
import { parseFEN } from "../fen.mjs";
import { draw } from "./draw";

const url = new URL(location.href);
const fen = url.searchParams.get("fen") || "8/8/8/8/8/8/8/8";
const squares = parseFEN(fen);

const options = makeOption({
	size: url.searchParams.get("size"),
	set: url.searchParams.get("set"),
	knightOffset: url.searchParams.get("knightOffset"),
	uncolored: url.searchParams.has("uncolored"),
	inverted: url.searchParams.has("inverted"),
	grayBG: url.searchParams.has("grayBG"),
	blackWhite: url.searchParams.has("blackWhite"),
})

const img = new Image();
img.onload = () => {
	const CN = draw(img, squares, options);
	CN.title = fen + "\n\nGenerated by https://mutsuntsai.github.io/fen-tool";
};
img.src = `../assets/${options.set}${options.size}.png`;
