const script = document.currentScript;
const apiURL = new URL("api/", script.src);
const globalOptions = script.dataset;

const frame = document.createElement("iframe");
frame.style.display = "none";

function setup(img) {
	const channel = new MessageChannel();
	channel.port1.onmessage = event => {
		img.src = event.data;
		img.title = fen + "\n\nGenerated by https://mutsuntsai.github.io/fen-tool";
	};
	const fen = img.getAttribute("fen");
	const options = Object.assign({}, globalOptions, img.dataset);
	frame.contentWindow.postMessage({ fen, options }, "*", [channel.port2]);
}

function check(node) {
	node.querySelectorAll("img[fen]").forEach(img => setup(img));
}

async function init() {
	document.body.appendChild(frame);
	await new Promise(resolve => {
		const handler = event => {
			if(event.source != frame.contentWindow) return;
			removeEventListener("message", handler);
			resolve();
		}
		addEventListener("message", handler);
		frame.src = apiURL.toString();
	});

	new MutationObserver(list => {
		for(const record of list) {
			if(record.type == "attributes") {
				const name = record.attributeName.toLowerCase();
				const isData = name.startsWith("data")
				if(record.target == script && isData) check(document);
				if(record.target.nodeName == "IMG" && (name == "fen" || isData)) setup(record.target);
			} else {
				for(const node of record.addedNodes) check(node);
			}
		}
	}).observe(document.documentElement, {
		childList: true,
		attributes: true,
		subtree: true
	});

	check(document);
}

addEventListener("DOMContentLoaded", init);
